### ISSUE TITLE
Compiler error "This usage of `list` is ambiguous"

### ISSUE THREAD

**Issue by APIPLM** [lassik/temp-aggregator-in-python#2]
The below is the process to run your Main.elm file in my site.

1. `elm init`
2. `elm install elm/http` `elm install elm/json`
3. place the file `Main.elm` of this repo to the folder `src/`
4. `elm make /root/bb/src/main.elm`

The error show up in the below
```
Detected problems in 1 module.
-- AMBIGUOUS NAME ------------------------------------------------- src/Main.elm

This usage of `list` is ambiguous:

228|     field "data" (list implDecoder)
                       ^^^^
This name is exposed by 2 of your imports, so I am not sure which one to use:

    Html.Attributes.list
    Json.Decode.list

I recommend using qualified names for imported values. I also recommend having
at most one `exposing (..)` per file to make name clashes like this less common
in the long run.

Note: Check out <https://elm-lang.org/0.19.1/imports> for more info on the
import syntax.
......
```

And also I checked the file `elm.json`, we use the same version of `elm`.
The version of the packages ( "elm/http": "2.0.0",   "elm/json": "1.1.3") are same, I supposed that  above error compiling related to both of them packages.  Anyway, the file `elm.json`  in my site is 
```
{
    "type": "application",
    "source-directories": [
        "src"
    ],
    "elm-version": "0.19.1",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.2",
            "elm/core": "1.0.5",
            "elm/html": "1.0.0",
            "elm/http": "2.0.0",
            "elm/json": "1.1.3"
        },
        "indirect": {
            "elm/bytes": "1.0.8",
            "elm/file": "1.0.5",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.2"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}


```
Could you have time to have a look? Thanks at advance.

**Comment by lassik** [comment]
Should be fixed now. Please try `git pull`.

**Comment by lassik** [comment]
Our current work to scrape SRFI data is at https://github.com/schemedoc/srfi-metadata. If you want to help with it, please join!

**Comment by APIPLM** [comment]
Thanks. I already pulled the latest code, and merge to the file `Main.elm` to my local repo. Now pass compiling the source file `Main.elm` in my side. But sound like need more work to figure out how it does work for me.

What you mentioned , the current work your guys are working on, it is like a different way to scrape SRFI metadata as I went through the repo. I would call that it is more natural comparing this temp version one. I would like to join. And also any questions, I will raise to you.

**Comment by APIPLM** [comment]
One comments `Cell(0 0)` in the table would be better like SRFI/Implementation platform.
One question as well, do we have like descriptions of relationship in the metadata like SRFI 13 and SRFI 135. I just saw like see-also in the file `data/srfi-data`. For search ability, for one SRFI it is much better for user to review the related SRFI.

**Comment by APIPLM** [comment]
Now it works in my site. I did not start  the server ` python3 serve.py`. After install bottle  `pip3 install bottle`, the server works. So I will close this issue.

**Comment by lassik** [comment]
No problem. Good to hear you got it working!
